'use strict';

const mongoose = require('mongoose');

require('dotenv').config();
mongoose.connect(process.env.DB_URL);

const Story = require('./model/Story.js');

async function seed() {

  await Story.create({
      title: 'The Story of Zippy and Layla',
      content: `Once upon a starry night, in the magnificent city of Dubai, a small spaceship descended from the heavens, carrying a friendly alien named Zippy. Zippy had traveled from a distant planet to Earth on a special mission: to protect art from being destroyed in the impending end-of-the-world apocalypse.
      
      As Zippy explored the bustling streets of Dubai, filled with towering skyscrapers and dazzling lights, they felt a sense of urgency. Zippy knew that precious artworks were hidden within these architectural wonders, waiting to be saved from the chaos that loomed ahead.
      
      By a stroke of fate, Zippy crossed paths with a brave and imaginative little girl named Layla. Layla's eyes sparkled with wonder and she had a deep love for art. Zippy knew they had found the perfect companion to aid them on their mission.
      
      Together, Zippy and Layla embarked on a thrilling adventure. They raced against time, traversing the city's vibrant markets, winding alleyways, and majestic art galleries. With each step, they encountered different forms of art—paintings, sculptures, and even mesmerizing performances.
      
      As they rescued one artwork after another, Zippy and Layla discovered the incredible power of creativity and love. The art they saved brought joy and inspiration to everyone they encountered, igniting a spark of hope amidst the impending doom.
      
      Finally, as the world stood on the edge of destruction, Zippy and Layla managed to preserve the last remaining masterpiece—a symbol of unity and resilience. As the apocalypse raged around them, they held hands, watching as the world transformed.
      
      In the end, Zippy and Layla emerged from the chaos, art clutched tightly in their hands. Their bravery and determination had saved the treasures of Dubai, preserving the beauty that lay within its walls. The art continued to inspire and unite people, even in the darkest of times, reminding everyone that creativity and love can withstand any storm.
      
      And so, the legend of Zippy and Layla spread far and wide, becoming a tale whispered by children at bedtime, reminding them of the enduring power of art and the importance of cherishing beauty in the world.`,
      date: 20230626,
      entry: 'Story was generated by ChatGPT'
  });
  console.log('First story was created');

  // await Story.create({
  //   title: '',
  //   content: '',
  //   date: 20230626,
  //   entry: ''
  // });
  // console.log('Second story was created');

  

  mongoose.disconnect();
}

seed(); 